# a= set()
# a.add(int(input("Enter the first number: ")))
# a.add(input("Enter the Second number: "))
# a.add(input("Enter the Third number: "))
# a.add(input("Enter the Fourth number: "))
# a.add(input("Enter the Fifth number: "))
# a.add(input("Enter the Sixth number: "))
# a.add(input("Enter the Seventh number: "))
# a.add(input("Enter the eighth number: "))
# print(a)

b=set()
b.add(18)
b.add("18")
b.add("18.0")
print(b)